### ISSUE TITLE
Ability pool is a complete mess

### ISSUE THREAD

**Issue by Fapboard** [darklordabc/Legends-of-Dota-Redux#1363] opened 2018-02-16 11:22 UTC
Should probably be a known factor by know, however i've seen nothing on the particular subject of what is currently adressing this or what will be done.

Lots of abilities are simply blank icons returning null values of being picked.
 - That means that you miss out on picking a real ability alltoghether.

Some abilities have vanished in this chaos, "Mount" i've heard has recieved a sad response of its current state.

While on the other hand "Shield", which is a Single-player marked ability is in the draft despite the mode not being enabled. Which allows you to go 100% damage reduction on your enemies fountain.

I do not know what caused this is the first place nor do I care.

It should just be adressed and corrected.

- Regards, Whiteboard.

**Comment by DankBudd** [comment] 2018-02-16 15:19
duplicate of #1356

**Comment by darklordabc** [comment] 2018-02-21 18:53
Closed because duplicate.

**Closed as completed by darklordabc** 2018-02-21 18:53 UTC
