### ISSUE TITLE
Bug:  Glaives of Wisdom with Death Prophet

### ISSUE THREAD

**Issue by leviathan13** [darklordabc/Legends-of-Dota-Redux#1437] opened 2018-04-12 16:05 UTC
The lvl25 talent "+1s glaives silence" add a 1s silence on hit with Glaives of Wisdom, but Death Prophet's perk doesn't work with that (glaives don't mute enemies).

**Comment by DankBudd** [comment] 2018-04-12 19:47
probably missing the 'silence' flag
https://github.com/darklordabc/Legends-of-Dota-Redux/blob/909bb0d15f393d31f7d29250b05a2c2bba59892b/src/game/scripts/vscripts/abilities/hero_perks/npc_dota_hero_death_prophet_perk.lua#L68

**Comment by darklordabc** [comment] 2018-05-15 06:05
@Wouterz90 any idea how to fix this? You made the DP perk.

**Comment by Wouterz90** [comment] 2018-05-17 16:11
Most likely it doesn't count as an ability

**Comment by Wouterz90** [comment] 2018-05-17 16:29
Should be fixed, let me know if I messed up something!

**Comment by ForbiddenFruitPOD** [comment] 2018-05-19 13:53
The perk still doesn't work with glaives of wisdom talent

**Comment by Wouterz90** [comment] 2018-05-29 19:40
I think I know what causes it, might be a bit annoying to fix it though. But I'll do it soon.

**Comment by Wouterz90** [comment] 2018-06-08 17:36
I have something that should work in theory, will test it tomorrow.

**Comment by Wouterz90** [comment] 2018-07-21 07:25
I'm sorry I forgot about this. The issue is that when there is no ability attached to the modifier like in this case, it won't trigger our system. Changing that would require a lot of work and opens us op to new bugs. I don't think that's the path we will  be taking. I'm sorry.

**Closed as completed by Wouterz90** 2018-07-21 07:25 UTC
Labels: bug, balance, hero perk
