### ISSUE TITLE
Single player mode seems to be unplayable

### ISSUE THREAD

**Issue by scaroxx8250** [darklordabc/Legends-of-Dota-Redux#1355] opened 2018-02-07 15:08 UTC
Hi guys.

First of all, thank you so much for all your ceaseless contributions to making this great game even better. LOD:R has brought me many hours of fun and stress relief for those nights when you just wanna feel like an OP mofo after a long day of being the bottom dog at work.

Here's my issue:
Every time I try to start a single player lobby, the game loads and brings me to the drafting stage as per usual. However, once that is over, one of two possible things happen - 

1. The game freezes at the loading screen, after the hero lineup showcase sound plays in the background. Mouse cursor can still move and ambient fountain sound effects are still playing, but the spinning icon on the loading screen remains stuck and the loading screen does not disappear. 

2. The game loads all heroes as per normal, but any hero perks/items that provide an aura/buff either have no icon, or have a red border instead of the usual green, or both. Within a few minutes of game starting, the entire game will freeze (with mouse cursor still movable) and I am unable to exit in-game without force closing the window.

Any ideas as to what is going on?

**Comment by DankBudd** [comment] 2018-02-07 16:30
this is something valve introduced in the spring cleaning update. we dont know exactly whats causing it, it seems like a lot of custom games are having similar problems.
we are hoping valve will fix these problems soon, and if they dont we will eventually figure something out.

i would suggest simply reconnecting, as some custom games have these problems fixed by disconnecting and reconnecting. unfortunately in lodr, there are other bugs that can occur when disconnecting before you get your hero spawned.

**Comment by angelbirth** [comment] 2018-02-07 18:18
duplicate of #1350

**Comment by jephat** [comment] 2018-02-10 02:09
the game until today is unplayable stuck or freeze the loading screen ,seem like valve reluctant to fix it ,they release an update yesterday but no fix had done to the custom game like lod redux or dota fun( all custom game that include bot ai)

**Comment by darklordabc** [comment] 2018-02-10 02:17
I've emailed valve and sent a Reddit message to.a valve employee. My hope is that Thursday when they do the patch they will have a fix for this issue.

**Comment by darklordabc** [comment] 2018-02-11 12:53
HOTFIX FOR CRASHING: You cannot have the LoD:R game page open in the background while you are playing the game, or else it corrupts the game. The theory is that the game page accesses the VPK (file format that contains the custom game) and that is somehow interfers with the clients ability to access the VPK (hence it can't open script files and it breaks many things). A hotfix is to change tabs before launching the game, like in this video: https://www.youtube.com/watch?v=qvgeGCvbwQ8&feature=youtu.be

**Closed as completed** 2018-08-06 16:24 UTC
Labels: bug, highest priority
