### ISSUE TITLE
Proteus Rarefaction Ability Bug

### ISSUE THREAD

**Issue by dongle-r** [darklordabc/Legends-of-Dota-Redux#1299] opened 2017-12-02 21:20 UTC
The custom ability Rarefaction, imported from The Next Generation hero concepts, does not provide the cool down reduction it says it does. When cast, the ability only makes the player take more damage.

**Comment by DankBudd** [comment] 2017-12-03 06:01
its only supposed to reduce cooldowns for proteus' abilities: razorwind, polyp, and jet
are you certain its not working for those abilities?

**Comment by dongle-r** [comment] 2017-12-03 06:12
This is one of those cases where the tool tip is miss leading, and also it is also broken in a different way then my original. The ability works for all abilities in the game, not just proteus' abilities. My miss understanding came from thinking that the ability cool down would be reduced for the duration of the ult, but instead, it only reduces the cool down of abilities that are currently on cool down. Example: Jet has 6 second cool down, ult is used, and it still has 6 second cool down. However, if Jet is used and is on cool down at 5 seconds remaining, ult is used, and it is immediately off cooldown.

**Comment by DankBudd** [comment] 2017-12-03 06:20
yes it seems you are right, it does work for all abilities i guess i remembered that wrong.
and yeah the tooltip could probably  be improved to make it clear that it reduces cooldowns, and doesnt give a % cooldown reduction.

**Comment by darklordabc** [comment] 2017-12-11 08:20
![image](https://user-images.githubusercontent.com/16277198/33821561-5aa0b200-dea8-11e7-8847-d17441b9abf5.png)
Closing this issue as the ability works as intended for me and it seems obvious to me that its 5 seconds reduction not 5%.

**Closed as completed by darklordabc** 2017-12-11 08:20 UTC
