### ISSUE TITLE
meepo perk error

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#925] opened 2017-04-18 01:44 UTC
[VScript] Script Runtime Error: ...cripts\abilities\hero_perks\npc_dota_hero_meepo_perk.lua:49: attempt to index global 'HeroList' (a nil value)
    stack traceback:
	    ...cripts\abilities\hero_perks\npc_dota_hero_meepo_perk.lua:49: in function <...cripts\abilities\hero_perks\npc_dota_hero_meepo_perk.lua:47>

herolist is probably server only or something

**Comment by darklordabc** [comment] 2017-04-18 05:05
Duplicate of #919

**Closed as completed by darklordabc** 2017-04-18 05:05 UTC
