### ISSUE TITLE
Burning Spell Blade

### ISSUE THREAD

**Issue by AugurM** [darklordabc/Legends-of-Dota-Redux#751] opened 2017-02-20 18:26 UTC
The spell never gets credited for a kill, in regard to the expected interaction with Lyon's perk for example.

Plus, the tooltip doesn't explain its working quite clearly.
What is Fire Damage?
How long does it stay?
What is the Day/Night difference?

**Comment by darklordabc** [comment] 2017-02-20 18:32
This might be one for @OtsoTurpeinen

**Comment by AugurM** [comment] 2017-02-20 18:51
They (Dark Spell Blade & Burning Spell Blade) might also be targeting invisible units with the bounces. I don't know if it is intended.

**Comment by OtsoTurpeinen** [comment] 2017-02-20 19:18
The fire damage was unique mechanic for Overflow (along with lightning and poison damage). It was explained in different location as it was shared by bunch of abilities. Might have to reconfigure it for this.
(especially when it was balanced with interaction between modifiers "element_fire" and "element_water" that occurred naturally from river or a bottle).
The part where it jumped at invisible units was intended (so you can't escape it just like you can't escape static link etc.)

Day and night differences for both is increased modifier stacks (burning spell blade at day, dark spell blade at night)

**Comment by AugurM** [comment] 2017-02-20 19:55
Well, the abilities are legitimately great, they just need clearer tooltips.

**Comment by darklordabc** [comment] 2017-03-28 08:27
@OtsoTurpeinen should we close this one? Your call.

**Closed as completed** 2018-08-06 16:20 UTC
Labels: bug, custom ability
